"""Initial schema

Revision ID: a33e27a5a327
Revises: 
Create Date: 2026-07-13 10:19:41.647399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33e27a5a327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('question_bank_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importer_user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('detected_delimiter', sa.String(length=4), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('topic_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['importer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_bank_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_imports_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_imports_imported_at'), ['imported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_imports_importer_user_id'), ['importer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_imports_status'), ['status'], unique=False)

    op.create_table('staged_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('detected_delimiter', sa.String(length=4), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('topic_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staged_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staged_imports_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_imports_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_staged_imports_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_import_id', sa.Integer(), nullable=False),
    sa.Column('external_question_id', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_a', sa.Text(), nullable=False),
    sa.Column('answer_b', sa.Text(), nullable=False),
    sa.Column('answer_c', sa.Text(), nullable=False),
    sa.Column('answer_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.String(length=20), nullable=True),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_import_id'], ['question_bank_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_import_id', 'external_question_id', name='uq_question_per_bank')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_active'), ['active'], unique=False)
        batch_op.create_index('ix_questions_bank_active', ['bank_import_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_bank_import_id'), ['bank_import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_content_fingerprint'), ['content_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_external_question_id'), ['external_question_id'], unique=False)
        batch_op.create_index('ix_questions_topic_key', ['topic_key'], unique=False)

    op.create_table('staged_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staged_import_id', sa.Integer(), nullable=False),
    sa.Column('external_question_id', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_a', sa.Text(), nullable=False),
    sa.Column('answer_b', sa.Text(), nullable=False),
    sa.Column('answer_c', sa.Text(), nullable=False),
    sa.Column('answer_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.String(length=20), nullable=True),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['staged_import_id'], ['staged_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staged_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staged_questions_staged_import_id'), ['staged_import_id'], unique=False)

    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('selected_topics', sa.JSON(), nullable=True),
    sa.Column('timed', sa.Boolean(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_reason', sa.String(length=20), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('adaptive_cold_start', sa.Boolean(), nullable=False),
    sa.Column('adaptive_metadata', sa.JSON(), nullable=True),
    sa.Column('bank_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_import_id'], ['question_bank_imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['test_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_sessions_bank_import_id'), ['bank_import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index('ix_test_sessions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_test_sessions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('test_session_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source_question_id', sa.Integer(), nullable=True),
    sa.Column('bank_import_id', sa.Integer(), nullable=True),
    sa.Column('external_question_id', sa.String(length=100), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_a', sa.Text(), nullable=False),
    sa.Column('answer_b', sa.Text(), nullable=False),
    sa.Column('answer_c', sa.Text(), nullable=False),
    sa.Column('answer_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('display_position', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_change_count', sa.Integer(), nullable=False),
    sa.Column('time_spent', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('is_unanswered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'display_position', name='uq_tsq_position'),
    sa.UniqueConstraint('session_id', 'external_question_id', name='uq_tsq_question')
    )
    with op.batch_alter_table('test_session_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_session_questions_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_tsq_external_id', ['external_question_id'], unique=False)
        batch_op.create_index('ix_tsq_fingerprint', ['content_fingerprint'], unique=False)
        batch_op.create_index('ix_tsq_session_position', ['session_id', 'display_position'], unique=False)
        batch_op.create_index('ix_tsq_topic_key', ['topic_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_session_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_tsq_topic_key')
        batch_op.drop_index('ix_tsq_session_position')
        batch_op.drop_index('ix_tsq_fingerprint')
        batch_op.drop_index('ix_tsq_external_id')
        batch_op.drop_index(batch_op.f('ix_test_session_questions_session_id'))

    op.drop_table('test_session_questions')
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_test_sessions_user_status')
        batch_op.drop_index(batch_op.f('ix_test_sessions_user_id'))
        batch_op.drop_index('ix_test_sessions_user_created')
        batch_op.drop_index(batch_op.f('ix_test_sessions_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_mode'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_bank_import_id'))

    op.drop_table('test_sessions')
    with op.batch_alter_table('staged_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_questions_staged_import_id'))

    op.drop_table('staged_questions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_topic_key')
        batch_op.drop_index(batch_op.f('ix_questions_external_question_id'))
        batch_op.drop_index(batch_op.f('ix_questions_content_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_questions_bank_import_id'))
        batch_op.drop_index('ix_questions_bank_active')
        batch_op.drop_index(batch_op.f('ix_questions_active'))

    op.drop_table('questions')
    with op.batch_alter_table('staged_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_imports_user_id'))
        batch_op.drop_index(batch_op.f('ix_staged_imports_token'))
        batch_op.drop_index(batch_op.f('ix_staged_imports_expires_at'))

    op.drop_table('staged_imports')
    with op.batch_alter_table('question_bank_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_imports_status'))
        batch_op.drop_index(batch_op.f('ix_question_bank_imports_importer_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_bank_imports_imported_at'))
        batch_op.drop_index(batch_op.f('ix_question_bank_imports_active'))

    op.drop_table('question_bank_imports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
